version: "3"

services:

  mongo:
    image: mongo
    restart: always

    ports:
      - 27017:27017

    networks:
      - usr

  flask-api:
    restart: always
    image: flask-api-microservice
    deploy:
      replicas: 5
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    build: .
    environment:
      - PYTHONUNBUFFERED=1
      - MODE=dev
      - MONGO_URL=mongo
      - MONGO_PORT=27017
      - SERVER_URL=0.0.0.0
      - ADMIN_USERNAME=admin
      - ADMIN_PASSWORD=pass

    volumes:
      - .:/code


    ports:
      - "2020:2020"

    networks:
      - usr
      



networks:
    usr:
        driver: bridge