swagger: "2.0"

info:
  title: "MentorMe API"
  description: "Find your next mentor!"
  version: "1.0"
  contact:
    name: Andrea Santilli and Fabrizo Lo Scudo
    email: andrea.santilli@live.it

  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html

basePath: /v1.0

schemes:
 - http
securityDefinitions:
  basicAuth:
    type: basic
    x-basicInfoFunc: api.utils.basic_auth

paths:
  /search:
    get:
      operationId: api.researcher.search_person
      parameters:
        - name: text
          in: query
          description: Name of a researcher (first and last name)
          required: true
          type: string

      responses:
        '200':
          description: 'Return a mentor from the database'
          schema:
            $ref: '#/definitions/MentorsList'


definitions:
  MentorsList:
    type: array
    items:
      type: object
      properties:
        author_id: { type: string }
        first: { type: string }
        last: { type: string }
        link: { type: string }
        middle: { type: string }